import com.vanniktech.maven.publish.GradlePlugin
import com.vanniktech.maven.publish.JavadocJar

plugins {
    id("prevham.kotlin.jvm")
    id("prevham.ktlint")
    id("prevham.publishing")
    id("java-gradle-plugin")
}

gradlePlugin {
    plugins {
        create("prevham") {
            id = "io.github.parkjiminnnn.prevham"
            implementationClass = "io.github.parkjiminnnn.gradle.PrevHamPlugin"
            displayName = "PrevHam"
            description = "Declares PrevHam's runtime, compiler and MockK dependencies."
        }
    }
}

mavenPublishing {
    coordinates(artifactId = "prevham-gradle-plugin")
    // GradlePlugin also publishes the plugin marker that `plugins { id(...) }` resolves, which is
    // what lets the plugin be applied from Maven Central rather than the Gradle Plugin Portal.
    configure(GradlePlugin(javadocJar = JavadocJar.Dokka("dokkaHtml")))

    pom {
        name.set("PrevHam Gradle Plugin")
        description.set("Applies PrevHam's dependencies so consumers declare one version instead of three.")
    }
}

// The plugin resolves prevham-runtime and prevham-compiler at its own version, so the three always
// move together. MockK's version comes from the same catalog the rest of the build uses.
val generateVersionConstants =
    tasks.register("generateVersionConstants") {
        val prevHamVersion = providers.provider { project.version.toString() }
        val mockkVersion = libs.versions.mockk
        val outputDir = layout.buildDirectory.dir("generated/versionConstants")

        inputs.property("prevHamVersion", prevHamVersion)
        inputs.property("mockkVersion", mockkVersion)
        outputs.dir(outputDir)

        doLast {
            val file = outputDir.get().file("io/github/parkjiminnnn/gradle/VersionConstants.kt").asFile
            file.parentFile.mkdirs()
            file.writeText(
                """
                package io.github.parkjiminnnn.gradle

                // Generated by the generateVersionConstants task - do not edit.
                internal const val PREVHAM_VERSION: String = "${prevHamVersion.get()}"
                internal const val MOCKK_VERSION: String = "${mockkVersion.get()}"
                """.trimIndent() + "\n",
            )
        }
    }

kotlin.sourceSets.named("main") { kotlin.srcDir(generateVersionConstants) }

dependencies {
    // compileOnly on purpose: bundling the KSP Gradle plugin would put its version on every
    // consumer's buildscript classpath, which is exactly the Kotlin-version pinning the plugin
    // avoids by having consumers declare KSP themselves.
    compileOnly(libs.ksp.gradlePlugin)

    testImplementation(libs.junit)
}

// TestKit needs the plugin under test on the test build's classpath.
gradlePlugin.testSourceSets(sourceSets["test"])
